### ISSUE TITLE
Easier liquid fueling

### ISSUE THREAD

**Issue by brachy84** [Cazadorsniper/Furnace-Overhaul#16] opened 2019-03-01 18:50 UTC
Could you make that when i put a bucket of fuel (or portable tank) in burn slot that the bucket emptys and the furnce tank fills up? Just because easier fueling

**Comment by Shadows-of-Fire** [comment] 2019-03-01 18:51
Duplicate of #14
(fixed but not released)

**Closed as completed by Shadows-of-Fire** 2019-03-01 18:51 UTC
